### ISSUE TITLE
raw_bytes sometimes combines fg and bg

### ISSUE THREAD

**Issue by fdncred** [rgwood/escape-artist#9]
I'm hovering over the FG icon. While technically correct because the raw bytes do show fg and bg, when you hover over FG, you expect to see just the FG escape.  If you hover over the BG icon, you see the same FG and BG escapes there too.
![Screenshot 2024-04-11 at 9 33 50 PM](https://github.com/rgwood/escape-artist/assets/343840/5c256193-7569-412e-8e85-13a97f65f482)
The tooltip top text is correct though, it is the appropriate FG or BG color, it's just the bottom of the tooltip, which I believe is the raw bytes that is incorrect.

**Comment by rgwood** [comment]
Yeah, I've considered mentioning this in the FAQ because it is a little unintuitive.

A single escape sequence can map to multiple [Actions](https://docs.rs/termwiz/latest/termwiz/escape/enum.Action.html) (as you mention, "the raw bytes do show fg and bg"), and Actions are what I end up displaying in the UI.

For this particular example of `\x1b[48;2;12;12;12;38;2;196;160;0m`, `48;2;12;12;12;` specifies the background and `38;2;196;160;0` specifies the foreground. But I don't want to _only_ show those bytes for the BG/FG actions because the surrounding `\x1b[ ... m` has meaning too.

I think the best that could be done is:
1. Work out which subsequence the action comes from (e.g. `48;2;12;12;12;` for the background) 
2. Show the whole sequence, but highlight the relevant subsequence

I'm probably not going to get to this anytime soon but it would be a nice bit of polish.

**Comment by fdncred** [comment]
Ah, ok, it's by design. I think that makes sense. It just threw me off when hovering. I've been doing some debugging of Escape Artist and it's clear that it knows, I guess through termwize, which is FG and which is BG. So, what you're saying about highlighting the relevant sequence should be doable.

As you can see here in my debug messages on the 38;2 and 48;2 lines, it's clear termwiz knows what's going on. Of course, because this is what's used for the top line of the tooltip.
![image](https://github.com/rgwood/escape-artist/assets/343840/f0ef4a3d-976f-4d4f-92a3-2cc2709021cf)


Just brainstorming here, but it may be cool to have a list of actions. In nushell style it may look something like this in a tooltip with "Active" showing which item you're hovering over. Maybe the "m" by itself is too much but you get the idea.
```nushell
╭─#─┬Action┬─────Bytes──────┬─────────Description──────────┬Active╮
│ 0 │ BG   │ 48;2;12;12;12  │ Set the background color     │      │
│ 1 │ FG   │ 38;2;196;160;0 │ Set the foreground color     │  ✅  │
│ 2 │ End  │ m              │ End the ansi escape sequence │      │
╰───┴──────┴────────────────┴──────────────────────────────┴──────╯
```
